# Display metadata for the public Senát 2026 experiment site.
# Probabilities are NOT stored here — build.py reads them from the vault forecast notes
# (single source of truth). This file holds only display names, parties and short texts.
#
# Per district: number, name, note (forecast file name), candidates {ascii_key: (display, party)},
# status_cs/en (incumbent / open seat), why_cs/en (short rationale), watch_cs/en (what to watch).

DISTRICTS = [
    dict(n=3, name="Cheb", note="2026-10-02-cheb-senat-obvod3-2026.md",
         cand={"Plevny": ("Jaroslav Plevný", "STAN, podpora ODS, KDU-ČSL, TOP 09, Piráti, Zelení"),
               "Tsoukernik": ("Tsoukernik", "ANO"),
               "Cerna": ("Černá", "VOK")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Obhájce s širokou koaliční podporou; druhé kolo v roce 2020 vyhrál 70 : 30. ANO má silnou základnu, ale ve druhých kolech dlouhodobě prohrává.",
         why_en="Incumbent with broad coalition backing; won the 2020 runoff 70–30. ANO has a strong base but a weak long-run runoff record.",
         watch_cs="Pořadí v 1. kole: vede-li Tsoukernik o 5+ bodů, klesá Plevný k ~55–62 %.",
         watch_en="Round-1 order: if Tsoukernik leads by 5+ pp, Plevný drops to ~55–62 %."),
    dict(n=6, name="Louny", note="2026-10-02-louny-senat-obvod6-2026.md",
         cand={"Tresl": ("Ivo Trešl", "STAN, podpora ODS"),
               "Mikolas": ("Mikoláš", "ANO"),
               "Steiner": ("Steiner", "Jsme PRO!")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Souboj obhájce s kandidátem ANO v okrese, kde je ANO silné. Rozhoduje, kdo povede po 1. kole.",
         why_en="Incumbent vs. ANO in an ANO-strong area; who leads after round 1 is decisive.",
         watch_cs="Vede-li Mikoláš po 1. kole, je to zhruba 50 : 50. Sledovat účast v Rakovnicku (Treślova základna).",
         watch_en="If Mikoláš leads after round 1 it is roughly a coin flip. Watch turnout around Rakovník (Trešl's base)."),
    dict(n=9, name="Plzeň-město", note="2026-10-02-plzen-mesto-senat-obvod9-2026.md",
         cand={"Aschenbrenner": ("Lumír Aschenbrenner", "ODS, TOP 09, Koruna Česká"),
               "Rehka": ("Karel Řehka", "nestraník, podpora STAN"),
               "Kantorova": ("Lucie Kantorová", "ANO"),
               "Pouskova": ("Daniela Pousková", "Pro Plzeň")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Obhájce se nejpravděpodobněji utká s Kantorovou (ANO), kterou by ve 2. kole měl porazit. Hlavní riziko: bývalý náčelník generálního štábu Řehka mu bere centristické voliče.",
         why_en="The incumbent most likely meets Kantorová (ANO) in the runoff and should beat her. Main risk: former Chief of General Staff Řehka splitting the centre-right vote.",
         watch_cs="Předběhne-li Řehka v 1. kole Aschenbrennera, stává se favoritem (~55 %).",
         watch_en="If Řehka finishes ahead of Aschenbrenner in round 1, he becomes the favourite (~55 %)."),
    dict(n=12, name="Strakonice", note="2026-10-02-strakonice-senat-obvod12-2026.md",
         cand={"Fiala": ("Tomáš Fiala", "Naše Česko (zvolen 2020 za ODS)"),
               "Hrdinova": ("Jana Hrdinová", "KDU-ČSL, podpora STAN"),
               "Usaty": ("Miroslav Ušatý", "Svobodní, podpora SPD, Trikolóra, PRO")},
         status_cs="obhájce běží; jen 3 kandidáti", status_en="incumbent running; only 3 candidates",
         why_cs="Jen tři kandidáti, ANO ani ODS nekandidují. Obhájce má reálnou šanci vyhrát už v 1. kole (~43 %).",
         why_en="Only three candidates; neither ANO nor ODS runs. The incumbent has a real chance of winning outright in round 1 (~43 %).",
         watch_cs="Fiala nad 50 % = rozhodnuto. Jinak záleží na soupeři ve 2. kole.",
         watch_en="Fiala above 50 % settles it; otherwise the runoff opponent matters."),
    dict(n=15, name="Pelhřimov", note="2026-10-02-pelhrimov-senat-obvod15-2026.md",
         cand={"Med": ("Med", "ODS, koalice Za demokracii (ODS, TOP 09, KDU, STAN, STO)"),
               "Chalupsky": ("Chalupský", "obhájce, Srdcem a Rozumem"),
               "Kozar": ("Kozár", "ANO"),
               "PavluRadova": ("Pavlů Řádová", "SPD")},
         status_cs="obhájce běží proti kandidátovi vlastního bloku", status_en="incumbent running against his own bloc's candidate",
         why_cs="Nejtěsnější obvod: koalice podporuje Meda proti obhájci Chalupskému. Kandidát ANO má ve 2. kole slabé vyhlídky.",
         why_en="One of the closest races: the coalition backs Med against incumbent Chalupský. The ANO candidate's runoff prospects are weak.",
         watch_cs="Pořadí Med vs. Chalupský v 1. kole prakticky rozhodne mandát.",
         watch_en="The Med vs. Chalupský order in round 1 will practically decide the seat."),
    dict(n=18, name="Příbram", note="2026-10-02-pribram-senat-obvod18-2026.md",
         cand={"Stepanek": ("Štěpánek", "STAN, podpora ODS"),
               "Danhova": ("Daňhová", "ANO"),
               "Luftova": ("Luftová", "Piráti + Zelení"),
               "Sorna": ("Šorna", "SPD + PRO")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Bloky jsou v okrese zhruba vyrovnané (krajské volby 2024), ale ANO ve 2. kolech výrazně ztrácí.",
         why_en="The blocs are roughly level locally (2024 regional vote), but ANO loses ground in runoffs.",
         watch_cs="Vede-li Daňhová po 1. kole, Štěpánek klesá k ~60 %.",
         watch_en="If Daňhová leads after round 1, Štěpánek drops to ~60 %."),
    dict(n=21, name="Praha 5", note="2026-10-02-praha-5-senat-obvod21-2026.md",
         cand={"Laska": ("Václav Láska", "SEN 21, obhájce"),
               "Sablik": ("Radko Sáblík", "ODS + STAN + KDU-ČSL"),
               "Sarapatka": ("Zdeněk Šarapatka", "TOP 09 + Piráti + LES"),
               "Broz": ("Lubomír Brož", "ANO")},
         status_cs="obhájce běží bez podpory stran", status_en="incumbent running without party support",
         why_cs="Láska má osobní značku, ale strany, které ho podpořily v roce 2020, teď stojí za jeho soupeři. Rozštěpený pravý střed.",
         why_en="Láska has a personal brand, but the parties that backed him in 2020 now back his rivals. Split centre-right field.",
         watch_cs="Láska první → ~65–70 %; Láska třetí → mimo hru. Podpory mezi koly.",
         watch_en="Láska first → ~65–70 %; Láska third → out. Endorsements between rounds."),
    dict(n=24, name="Praha 9", note="2026-10-02-praha-9-senat-obvod24-2026.md",
         cand={"Smoljak": ("David Smoljak", "STAN, podpora Piráti, TOP 09, KDU-ČSL, Zelení"),
               "Peckova": ("Dagmar Pecková", "nestr., za ODS"),
               "Zalud": ("Radek Žalud", "ANO")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Nejpravděpodobnější 2. kolo Smoljak vs. Pecková. ODS je v Praze 9 lokálně silná a 1. kolo se koná s komunálními volbami.",
         why_en="Most likely runoff: Smoljak vs. Pecková. ODS is locally strong in Praha 9, and round 1 coincides with municipal elections.",
         watch_cs="Pecková první → favoritka (~60 %); Žalud druhý → Smoljak ~90 %.",
         watch_en="Pecková first → she is the favourite (~60 %); Žalud second → Smoljak ~90 %."),
    dict(n=27, name="Praha 1", note="2026-10-02-praha-1-senat-obvod27-2026.md",
         cand={"J_Cizinsky": ("Jan Čižinský", "Praha sobě + KDU-ČSL + Zelení"),
               "Padevet": ("Jiří Padevět", "STAN, podpora ODS, TOP 09, Piráti"),
               "Dudra": ("Ján Dudra", "ANO")},
         status_cs="volné místo (Němcová nekandiduje)", status_en="open seat (Němcová not running)",
         why_cs="Souboj dvou silných kandidátů; Čižinský má silnou základnu v Praze 7. Odhad se po red-teamu otočil (z 48 : 49).",
         why_en="Two strong candidates; Čižinský has a strong base in Praha 7. The lead flipped after the red-team (from 48–49).",
         watch_cs="Kdo vede 1. kolo, má ~70 %. Rozdíl Praha 7 vs. Praha 1.",
         watch_en="Whoever leads round 1 gets ~70 %. Praha 7 vs. Praha 1 margins."),
    dict(n=30, name="Kladno", note="2026-10-02-sipova-senat-kladno-obvod30-2026-v2.md",
         cand={"Sipova": ("Adéla Sucharda Šípová", "obhájkyně (dříve Piráti)"),
               "Gerloch": ("Gerloch", "ANO"),
               "Patak": ("Paták", "ODS")},
         status_cs="obhájkyně běží", status_en="incumbent running",
         why_cs="Tříčlenný souboj. Šípová je mírná favoritka; klíčové je, zda se ve 2. kole utká s ANO (lepší pro ni), nebo s ODS.",
         why_en="Three-way race. Šípová is a slight favourite; the key is whether her runoff opponent is ANO (better for her) or ODS.",
         watch_cs="Kdo obsadí druhé postupové místo (Gerloch vs. Paták).",
         watch_en="Who takes the second runoff slot (Gerloch vs. Paták)."),
    dict(n=33, name="Děčín", note="2026-10-02-decin-senat-obvod33-2026.md",
         cand={"Linhart": ("Zbyněk Linhart", "STAN + SLK"),
               "Hejcman": ("Michal Hejcman", "nestr., za ANO"),
               "Lehka": ("Anna Lehká", "MÍSTNÍ")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Obhájce v roce 2020 vyhrál už v 1. kole (52,8 %). ANO je v okrese silné, ale druhé kolo by Linhart pravděpodobně vyhrál.",
         why_en="The incumbent won outright in round 1 in 2020 (52.8 %). ANO is strong locally, but Linhart would likely win a runoff.",
         watch_cs="Vede-li Hejcman 1. kolo, Linhart klesá k ~45 %.",
         watch_en="If Hejcman leads round 1, Linhart drops to ~45 %."),
    dict(n=36, name="Česká Lípa", note="2026-10-02-ceska-lipa-senat-obvod36-2026.md",
         cand={"Puta": ("Martin Půta", "SLK, hejtman"),
               "Volfova": ("Jitka Volfová", "ANO, podpora SPD"),
               "Vosecky": ("Jiří Vosecký", "obhájce, nezávislý (dříve SLK)"),
               "Vomacka": ("Vít Vomáčka", "ODS")},
         status_cs="obhájce běží jako nezávislý", status_en="incumbent running as an independent",
         why_cs="Volfová (ANO) téměř jistě postoupí, ale ve 2. kole je slabší. Rizika pro Půtu: nepravomocné odsouzení (odvolání) a Vosecký, který mu může vzít postup.",
         why_en="Volfová (ANO) will almost surely advance but is weaker in a runoff. Risks for Půta: a non-final conviction (under appeal) and Vosecký taking a runoff slot.",
         watch_cs="Půta první → 80+ %; Vosecký před Půtou → ~50 %.",
         watch_en="Půta first → 80+ %; Vosecký ahead of Půta → ~50 %."),
    dict(n=39, name="Trutnov", note="2026-10-02-trutnov-senat-obvod39-2026.md",
         cand={"Sobotka": ("Jan Sobotka", "STAN, podpora ODS, KDU-ČSL, TOP 09"),
               "Chovancova": ("Zuzana Chovancová", "ANO"),
               "Mraz": ("Radek Mráz", "SPD")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Silný obhájce (2020: 41,7 % v 1. kole, 74,6 % ve 2.). Šance na výhru už v 1. kole kolem 31 %.",
         why_en="Strong incumbent (2020: 41.7 % in round 1, 74.6 % in the runoff). About a 31 % chance of an outright round-1 win.",
         watch_cs="Vede-li Chovancová, Sobotka klesá k ~45–50 %.",
         watch_en="If Chovancová leads, Sobotka drops to ~45–50 %."),
    dict(n=42, name="Kolín", note="2026-10-02-kolin-senat-obvod42-2026.md",
         cand={"Kaspar": ("Michael Kašpar", "STAN, starosta Kolína"),
               "Brzobohata": ("Andrea Brzobohatá", "ANO"),
               "Schulz": ("Roman Schulz", "ODS + TOP 09, starosta Poděbrad"),
               "Sehnal": ("Pavel Sehnal", "Aliance pro budoucnost")},
         status_cs="volné místo (Kárník nekandiduje)", status_en="open seat (Kárník not running)",
         why_cs="Starosta Kolína je jasný favorit; hlavní riziko je 2. kolo proti Schulzovi (pravý střed proti pravému středu).",
         why_en="The mayor of Kolín is a clear favourite; the main risk is a runoff against Schulz (centre-right vs. centre-right).",
         watch_cs="Kašpar vede o 10+ bodů → 92+ %; souboj se Schulzem → ~53 %.",
         watch_en="Kašpar leads by 10+ pp → 92+ %; runoff against Schulz → ~53 %."),
    dict(n=45, name="Hradec Králové", note="2026-10-02-hradec-kralove-senat-obvod45-2026.md",
         cand={"Dvorak": ("Dvořák", "STAN, podpora Piráti, TOP 09, Zelení, HDK"),
               "Holasek": ("Holásek", "obhájce, Rozvíjíme Hradec"),
               "Ceralova_Petrofova": ("Ceralová Petrofová", "nestr., podpora ODS"),
               "Hulkova": ("Hůlková", "ANO")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Tři kandidáti pravého středu se dělí o voliče; Hůlková (ANO) postoupí asi v 79 % scénářů, ale 2. kolo vyhrává jen zřídka.",
         why_en="Three centre-right candidates split the vote; Hůlková (ANO) reaches the runoff in ~79 % of scenarios but rarely wins it.",
         watch_cs="Kdo z pravého středu skončí v 1. kole první; souboj Dvořák vs. Holásek je zhruba 50 : 50.",
         watch_en="Which centre-right candidate finishes first; Dvořák vs. Holásek is roughly a coin flip."),
    dict(n=48, name="Rychnov nad Kněžnou", note="2026-10-02-rychnov-nad-kneznou-senat-obvod48-2026.md",
         cand={"Grulich": ("Jan Grulich", "TOP 09, podpora ODS, KDU-ČSL, STAN, Piráti, LES"),
               "Sadovsky": ("Petr Sadovský", "ANO")},
         status_cs="obhájce běží; jen 2 kandidáti — rozhodne 1. kolo", status_en="incumbent running; only 2 candidates — round 1 decides",
         why_cs="Jen dva kandidáti, takže rozhodne přímo 1. kolo. Model převádí výsledek sněmovních voleb 2025 v okrese na dva kandidáty, přičemž v senátních volbách obvykle oslabuje vládní strana.",
         why_en="Only two candidates, so round 1 decides. The model maps the 2025 Chamber result onto two candidates, with the usual Senate swing against the governing party.",
         watch_cs="Výsledek 1. kola 10. 10. je konečný.",
         watch_en="The round-1 result on 10 Oct is final."),
    dict(n=51, name="Žďár nad Sázavou", note="2026-10-02-zdar-nad-sazavou-senat-obvod51-2026.md",
         cand={"Klement": ("Josef Klement", "KDU-ČSL, podpora STAN"),
               "Smarda": ("Michal Šmarda", "SOM + Volt + Hlas regionů"),
               "Koten": ("Radek Koten", "SPD"),
               "Cerny": ("Radek Černý", "ODS + Piráti + STO")},
         status_cs="obhájce běží; ANO nekandiduje", status_en="incumbent running; no ANO candidate",
         why_cs="Repríza roku 2020 (Klement porazil Šmardu 59,8 : 40,2). ANO tu nemá kandidáta.",
         why_en="A rematch of 2020 (Klement beat Šmarda 59.8–40.2). ANO fields no candidate.",
         watch_cs="Vede-li Šmarda po 1. kole, Klement klesá k ~45 %.",
         watch_en="If Šmarda leads after round 1, Klement drops to ~45 %."),
    dict(n=54, name="Znojmo", note="2026-10-02-znojmo-senat-obvod54-2026.md",
         cand={"Tretina": ("Tomáš Třetina", "TOP 09, koalice Znojemsko pohromadě"),
               "Kynera": ("Jiří Kyněra", "ANO"),
               "Beranova": ("Bohumila Beranová", "Hlas regionů")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Kyněra je jedinou volbou pro vládní voliče (SPD ani Motoristé nekandidují), ale obhájce s širokou koalicí je favorit.",
         why_en="Kyněra is the only option for government voters (no SPD or Motoristé candidate), but the broadly backed incumbent is favoured.",
         watch_cs="Vede-li Kyněra, Třetina klesá k ~42 %.",
         watch_en="If Kyněra leads, Třetina drops to ~42 %."),
    dict(n=57, name="Vyškov", note="2026-10-02-vyskov-senat-obvod57-2026.md",
         cand={"Grolich": ("Jan Grolich", "KDU-ČSL, hejtman, podpora STAN, ODS, TOP 09"),
               "Absolonova": ("Petra Absolonová", "ANO"),
               "Fladr": ("Jaroslav Fládr", "PŘÍSAHA")},
         status_cs="volné místo (Zitterbart kandiduje v Brně)", status_en="open seat (Zitterbart runs in Brno)",
         why_cs="Bloky, které se v roce 2020 dělily, teď stojí za jedním kandidátem. Šance na výhru v 1. kole ~50 %.",
         why_en="Blocs that split in 2020 now back a single candidate. ~50 % chance of an outright round-1 win.",
         watch_cs="Grolich nad 50 % = rozhodnuto; vede-li Absolonová, ~58 %.",
         watch_en="Grolich above 50 % settles it; if Absolonová leads, ~58 %."),
    dict(n=60, name="Brno-město", note="2026-10-02-brno-mesto-senat-obvod60-2026-v2.md",
         cand={"Papousek": ("Zdeněk Papoušek", "obhájce, ODS/KDU-ČSL/TOP 09/Piráti"),
               "Sterba": ("Štěrba", "ANO"),
               "Zitterbart": ("Karel Zitterbart", "STAN (přechází z Vyškova)")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Obhájce v městském obvodě, kde ANO v roce 2024 ve 2. kole prohrálo 32 : 68. Druhé postupové místo je otevřené.",
         why_en="Incumbent in an urban district where ANO lost the 2024 runoff 32–68. The second runoff slot is open.",
         watch_cs="Kdo skončí druhý: Štěrba, nebo Zitterbart.",
         watch_en="Who finishes second: Štěrba or Zitterbart."),
    dict(n=63, name="Přerov", note="2026-10-02-prerov-senat-obvod63-2026.md",
         cand={"Navarik": ("Jakub Navařík", "ODS, podpora KDU-ČSL, STAN, TOP 09"),
               "Vrana": ("Petr Vrána", "ANO, primátor Přerova")},
         status_cs="volné místo (Seitlová končí)", status_en="open seat (Seitlová retiring)",
         why_cs="Vrána pravděpodobně vyhraje 1. kolo, ale ANO tu ve 2. kolech prohrálo 0 : 2 a celkově vyhrává jen ~20 % 2. kol.",
         why_en="Vrána likely wins round 1, but ANO is 0–2 in runoffs here and wins only ~20 % of runoffs overall.",
         watch_cs="Vede-li Navařík → 80–85 %; vede-li Vrána o 8+ bodů nad 43 % → ~45–50 %.",
         watch_en="If Navařík leads → 80–85 %; if Vrána leads by 8+ pp above 43 % → ~45–50 %."),
    dict(n=66, name="Litovel", note="2026-10-02-litovel-senat-obvod66-2026.md",
         cand={"Ostadal": ("Marek Ošťádal", "obhájce, hnutí 24/7 (odešel ze STAN)"),
               "Kohajda": ("Michael Kohajda", "KDU-ČSL, podpora ODS, TOP 09, Piráti; rektor UP"),
               "Skurek": ("Martin Škurek", "ANO, náměstek hejtmana")},
         status_cs="obhájce běží bez podpory stran", status_en="incumbent running without party support",
         why_cs="Velmi těsné: Ošťádal vs. Kohajda o místo ve 2. kole proti Škurkovi, který postoupí asi v 70 % scénářů, ale 2. kolo vyhrává zřídka.",
         why_en="Very close: Ošťádal vs. Kohajda for the runoff slot against Škurek, who advances in ~70 % of scenarios but rarely wins a runoff.",
         watch_cs="Kdo z dvojice Ošťádal/Kohajda postoupí.",
         watch_en="Which of Ošťádal/Kohajda advances."),
    dict(n=69, name="Frýdek-Místek", note="2026-10-02-frydek-mistek-senat-obvod69-2026.md",
         cand={"Pesatova": ("Helena Pešatová", "STAN + Piráti + TOP 09"),
               "Korc": ("Petr Korč", "Naše město F-M"),
               "Krpel": ("Tomáš Krpel", "SPD")},
         status_cs="obhájkyně běží; ANO ani ODS nekandidují", status_en="incumbent running; no ANO or ODS candidate",
         why_cs="Bez kandidáta ANO a ODS; Korč je hlavní soupeř a útočiště pro voliče ANO ve 2. kole.",
         why_en="No ANO or ODS candidate; Korč is the main rival and the runoff refuge for ANO voters.",
         watch_cs="Náskok Pešatové 10+ bodů → 85–90 %; pod 5 bodů → 60–65 %.",
         watch_en="Pešatová lead of 10+ pp → 85–90 %; under 5 pp → 60–65 %."),
    dict(n=72, name="Ostrava-město", note="2026-10-02-ostrava-mesto-senat-obvod72-2026.md",
         cand={"Simetka": ("Ondřej Šimetka", "nestr., za ODS, podpora KDU-ČSL, STAN, Piráti, TOP 09"),
               "Barankova_Vilamova": ("Lucie Baránková Vilamová", "ANO, starostka Poruby"),
               "Loprais": ("Milan Loprais", "PRO, podpora SPD")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Ostravská bilance ANO ve 2. kolech je lepší než celostátní, ale v letech, kdy vládne, slabá. Baránková má základnu v Porubě.",
         why_en="ANO's Ostrava runoff record is better than nationally but weak in governing years. Baránková's base is Poruba.",
         watch_cs="Baránková vede o 5+ bodů → ~62 : 35; Šimetka vede o 5+ → 85–88 %.",
         watch_en="Baránková leads by 5+ pp → ~62–35; Šimetka leads by 5+ → 85–88 %."),
    dict(n=75, name="Karviná", note="2026-10-02-karvina-senat-obvod75-2026.md",
         cand={"Brzyszkowska": ("Lenka Brzyszkowská", "ANO, starostka Orlové"),
               "Polach": ("Polách", "za ODS, Pro Karvinsko"),
               "Szyja": ("Szyja", "za Piráty, podpora Zelení, STAN, TOP 09, SEN 21"),
               "Kazik": ("Kazík", "Osobnosti pro kraj"),
               "Stanek": ("Staněk", "SPD")},
         status_cs="volné místo ANO (Feber nekandiduje)", status_en="open ANO-held seat (Feber not running)",
         why_cs="Jediný obvod, kde je favoritkou kandidátka ANO: silná lokální základna a rozdělená opozice. V roce 2020 rozhodlo 84 hlasů při účasti 7,7 %.",
         why_en="The only district with an ANO favourite: a strong local base and a split opposition. In 2020 the runoff was decided by 84 votes at 7.7 % turnout.",
         watch_cs="Náskok v 1. kole: 20+ bodů → 75+ %; pod 10 bodů → zhruba 50 : 50. Dohoda Polách–Szyja.",
         watch_en="Round-1 margin: 20+ pp → 75+ %; under 10 pp → about a coin flip. A Polách–Szyja deal."),
    dict(n=78, name="Zlín", note="2026-10-02-zlin-senat-obvod78-2026.md",
         cand={"Golan": ("Tomáš Goláň", "ODS, koalice KDU-ČSL + ODS + TOP 09"),
               "Sedlarik": ("Vladimír Sedlařík", "nestr., za ANO; bývalý rektor UTB"),
               "Mitacek": ("Ivo Mitáček", "STAN")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Obhájce proti silnému kandidátovi ANO; primátor Korec (ANO) vede komunální kandidátku ve stejný den.",
         why_en="Incumbent vs. a strong ANO candidate; Mayor Korec (ANO) heads the municipal list on the same day.",
         watch_cs="Sedlařík před Goláněm → Goláň ~58 %.",
         watch_en="Sedlařík ahead of Goláň → Goláň ~58 %."),
    dict(n=81, name="Uherské Hradiště", note="2026-10-02-uherske-hradiste-senat-obvod81-2026.md",
         cand={"Bazala": ("Josef Bazala", "KDU-ČSL, podpora STAN, TOP 09"),
               "Vasica": ("Jiří Vašica", "ANO"),
               "Balastikova": ("Margita Balaštíková", "Odvážné Česko")},
         status_cs="obhájce běží", status_en="incumbent running",
         why_cs="Obhájce v baště KDU-ČSL proti nováčkovi za ANO; bývalá poslankyně ANO Balaštíková kandiduje za jinou stranu.",
         why_en="Incumbent in a KDU-ČSL stronghold vs. an ANO newcomer; former ANO MP Balaštíková runs for another party.",
         watch_cs="Je-li Vašica do 5 bodů za Bazalou, 2. kolo se zúží na ~65–70 %.",
         watch_en="If Vašica is within 5 pp of Bazala, the runoff tightens to ~65–70 %."),
]
